/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ResourcesRouteRouteImport } from './routes/resources/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesFolderIdRouteImport } from './routes/resources/$folderId'
import { Route as ApiFormsMembershipRouteImport } from './routes/api/forms/membership'
import { Route as ApiFormsContactRouteImport } from './routes/api/forms/contact'
import { Route as ApiPublicDriveFolderFolderIdRouteImport } from './routes/api/public/drive-folder.$folderId'
import { Route as ApiPublicDriveFileFileIdRouteImport } from './routes/api/public/drive-file.$fileId'

const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRouteRoute = ResourcesRouteRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const ResourcesFolderIdRoute = ResourcesFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const ApiFormsMembershipRoute = ApiFormsMembershipRouteImport.update({
  id: '/api/forms/membership',
  path: '/api/forms/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsContactRoute = ApiFormsContactRouteImport.update({
  id: '/api/forms/contact',
  path: '/api/forms/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveFolderFolderIdRoute =
  ApiPublicDriveFolderFolderIdRouteImport.update({
    id: '/api/public/drive-folder/$folderId',
    path: '/api/public/drive-folder/$folderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDriveFileFileIdRoute =
  ApiPublicDriveFileFileIdRouteImport.update({
    id: '/api/public/drive-file/$fileId',
    path: '/api/public/drive-file/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/journey': typeof JourneyRoute
  '/resources/$folderId': typeof ResourcesFolderIdRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/forms/contact': typeof ApiFormsContactRoute
  '/api/forms/membership': typeof ApiFormsMembershipRoute
  '/api/public/drive-file/$fileId': typeof ApiPublicDriveFileFileIdRoute
  '/api/public/drive-folder/$folderId': typeof ApiPublicDriveFolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/resources/$folderId': typeof ResourcesFolderIdRoute
  '/resources': typeof ResourcesIndexRoute
  '/api/forms/contact': typeof ApiFormsContactRoute
  '/api/forms/membership': typeof ApiFormsMembershipRoute
  '/api/public/drive-file/$fileId': typeof ApiPublicDriveFileFileIdRoute
  '/api/public/drive-folder/$folderId': typeof ApiPublicDriveFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/journey': typeof JourneyRoute
  '/resources/$folderId': typeof ResourcesFolderIdRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/forms/contact': typeof ApiFormsContactRoute
  '/api/forms/membership': typeof ApiFormsMembershipRoute
  '/api/public/drive-file/$fileId': typeof ApiPublicDriveFileFileIdRoute
  '/api/public/drive-folder/$folderId': typeof ApiPublicDriveFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resources'
    | '/journey'
    | '/resources/$folderId'
    | '/resources/'
    | '/api/forms/contact'
    | '/api/forms/membership'
    | '/api/public/drive-file/$fileId'
    | '/api/public/drive-folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journey'
    | '/resources/$folderId'
    | '/resources'
    | '/api/forms/contact'
    | '/api/forms/membership'
    | '/api/public/drive-file/$fileId'
    | '/api/public/drive-folder/$folderId'
  id:
    | '__root__'
    | '/'
    | '/resources'
    | '/journey'
    | '/resources/$folderId'
    | '/resources/'
    | '/api/forms/contact'
    | '/api/forms/membership'
    | '/api/public/drive-file/$fileId'
    | '/api/public/drive-folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResourcesRouteRoute: typeof ResourcesRouteRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  ApiFormsContactRoute: typeof ApiFormsContactRoute
  ApiFormsMembershipRoute: typeof ApiFormsMembershipRoute
  ApiPublicDriveFileFileIdRoute: typeof ApiPublicDriveFileFileIdRoute
  ApiPublicDriveFolderFolderIdRoute: typeof ApiPublicDriveFolderFolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/resources/$folderId': {
      id: '/resources/$folderId'
      path: '/$folderId'
      fullPath: '/resources/$folderId'
      preLoaderRoute: typeof ResourcesFolderIdRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/api/forms/membership': {
      id: '/api/forms/membership'
      path: '/api/forms/membership'
      fullPath: '/api/forms/membership'
      preLoaderRoute: typeof ApiFormsMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/contact': {
      id: '/api/forms/contact'
      path: '/api/forms/contact'
      fullPath: '/api/forms/contact'
      preLoaderRoute: typeof ApiFormsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-folder/$folderId': {
      id: '/api/public/drive-folder/$folderId'
      path: '/api/public/drive-folder/$folderId'
      fullPath: '/api/public/drive-folder/$folderId'
      preLoaderRoute: typeof ApiPublicDriveFolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-file/$fileId': {
      id: '/api/public/drive-file/$fileId'
      path: '/api/public/drive-file/$fileId'
      fullPath: '/api/public/drive-file/$fileId'
      preLoaderRoute: typeof ApiPublicDriveFileFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteRouteChildren {
  ResourcesFolderIdRoute: typeof ResourcesFolderIdRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteRouteChildren: ResourcesRouteRouteChildren = {
  ResourcesFolderIdRoute: ResourcesFolderIdRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteRouteWithChildren = ResourcesRouteRoute._addFileChildren(
  ResourcesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResourcesRouteRoute: ResourcesRouteRouteWithChildren,
  JourneyRoute: JourneyRoute,
  ApiFormsContactRoute: ApiFormsContactRoute,
  ApiFormsMembershipRoute: ApiFormsMembershipRoute,
  ApiPublicDriveFileFileIdRoute: ApiPublicDriveFileFileIdRoute,
  ApiPublicDriveFolderFolderIdRoute: ApiPublicDriveFolderFolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
