/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesFolderIdRouteImport } from './routes/resources.$folderId'
import { Route as ApiPublicDriveFileFileIdRouteImport } from './routes/api/public/drive-file.$fileId'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesFolderIdRoute = ResourcesFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => ResourcesRoute,
} as any)
const ApiPublicDriveFileFileIdRoute =
  ApiPublicDriveFileFileIdRouteImport.update({
    id: '/api/public/drive-file/$fileId',
    path: '/api/public/drive-file/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/resources/$folderId': typeof ResourcesFolderIdRoute
  '/api/public/drive-file/$fileId': typeof ApiPublicDriveFileFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/resources/$folderId': typeof ResourcesFolderIdRoute
  '/api/public/drive-file/$fileId': typeof ApiPublicDriveFileFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/resources/$folderId': typeof ResourcesFolderIdRoute
  '/api/public/drive-file/$fileId': typeof ApiPublicDriveFileFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journey'
    | '/resources'
    | '/resources/$folderId'
    | '/api/public/drive-file/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journey'
    | '/resources'
    | '/resources/$folderId'
    | '/api/public/drive-file/$fileId'
  id:
    | '__root__'
    | '/'
    | '/journey'
    | '/resources'
    | '/resources/$folderId'
    | '/api/public/drive-file/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JourneyRoute: typeof JourneyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ApiPublicDriveFileFileIdRoute: typeof ApiPublicDriveFileFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$folderId': {
      id: '/resources/$folderId'
      path: '/$folderId'
      fullPath: '/resources/$folderId'
      preLoaderRoute: typeof ResourcesFolderIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/api/public/drive-file/$fileId': {
      id: '/api/public/drive-file/$fileId'
      path: '/api/public/drive-file/$fileId'
      fullPath: '/api/public/drive-file/$fileId'
      preLoaderRoute: typeof ApiPublicDriveFileFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesFolderIdRoute: typeof ResourcesFolderIdRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesFolderIdRoute: ResourcesFolderIdRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JourneyRoute: JourneyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ApiPublicDriveFileFileIdRoute: ApiPublicDriveFileFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
